### ISSUE TITLE
Implement basic operations on core graph representation

### ISSUE THREAD

**Issue by HarryMcCarney** [fslaborg/Graphoscope#6]
Further to [this ](https://github.com/fslaborg/Graphoscope/discussions/3) discussion implement agreed syntax for 

- Add Node 
- Get Edge 
- Create Edge 
- Get Weight
- Get Neighbours
- Get Degree

**Comment by mikk-c** [comment]
You're probably working on this, but on my tests Measures.Degree.maximum seems to give incorrect results on DiGraph (I'm assuming this function is supposed to be run only on FGraph, or that DiGraph support is coming). I tried the following code:

```
#r "nuget: Graphoscope"
#r "nuget: FSharpAux.IO"

open Graphoscope
open FSharpAux.IO
open FSharpAux.IO.SchemaReader.Attribute

type MonkeyEdge = {
    [<Field(0)>] Source  : int
    [<Field(1)>] Target  : int
    [<Field(2)>] Groomed : int
}

let monkeyEdges =
    Seq.fromFileWithCsvSchema<MonkeyEdge>("out.moreno_rhesus_rhesus",' ',false,skipLines=2 )

let monkeyDiGraph =
    monkeyEdges
    |> Seq.map (fun mke ->
        mke.Source, sprintf "Monkey_%i" mke.Source,mke.Target,sprintf "Monkey_%i" mke.Target,float mke.Groomed)
    |> DiGraph.ofSeq

let maxDi = Measures.Degree.maximum monkeyDiGraph

printfn "%f" maxDi
```

This prints  "20".

The expected output is difficult to describe, because it is "10" if we want the indegree, or "12" if we want the outdegree, which isn't specified. But it is not 20 in either case (it seems that the code takes the maximum indegree and multiplies by 2).
